# Adds scrips for setting up the db for Myaku to the base mongo image.

FROM mongo:4.0.10

COPY ./docker/myaku_mongo-myakudb/run_myaku_mongo_seed.sh \
    /docker-entrypoint-initdb.d/

ENV SCRIPTS_DIR /scripts
ENV MYAKU_MONGO_SEED_JS_PATH $SCRIPTS_DIR/myaku_mongo_seed.js
COPY ./docker/myaku_mongo-myakudb/myaku_mongo_seed.js $MYAKU_MONGO_SEED_JS_PATH
