# Builds a reibun container image for development use.

FROM friedrice2/reibun-crawler.base:latest

# Volume for sharing in development source on host with container.
# Should be a read-only bind.
VOLUME ["$REIBUN_SRC_DIR"]

# Volume for persisting data only used in development such as ipython history.
ENV REIBUN_DEV_DATA_DIR $REIBUN_BASE_DIR/devdata
ENV IPYTHONDIR $REIBUN_DEV_DATA_DIR/ipython
VOLUME ["$REIBUN_DEV_DATA_DIR"]
