# Builds a reibun container image for production use.

FROM friedrice2/reibun/base

# Copy full source into image
COPY . $REIBUN_SRC_DIR

# 200 MB
ENV DEBUG_LOG_MAX_SIZE 200000000

# 20 MB
ENV INFO_LOG_MAX_SIZE 20000000
