# Adds scrips for setting up the db for Reibun to the base mongo image.

FROM mongo:4.0.10

COPY ./docker/setup_scripts/run_reibun_mongo_seed.sh \
    /docker-entrypoint-initdb.d/

ENV SCRIPTS_DIR /scripts
ENV REIBUN_MONGO_SEED_JS_PATH $SCRIPTS_DIR/reibun_mongo_seed.js
COPY ./docker/setup_scripts/reibun_mongo_seed.js $REIBUN_MONGO_SEED_JS_PATH
