# Builds a a crawler container image for dev use

FROM friedrice2/reibun/base

ENV REIBUN_SRC_DIR $REIBUN_BASE_DIR/src
VOLUME ["$REIBUN_SRC_DIR"]

ENV REIBUN_DEV_CONFIG_DIR $REIBUN_BASE_DIR/devconf
ENV IPYTHONDIR $REIBUN_DEV_CONFIG_DIR/ipython
VOLUME ["$REIBUN_DEV_CONFIG_DIR"]

COPY ./requirements.txt $REIBUN_SRC_DIR/
RUN python3.7 -m pip install -r $REIBUN_SRC_DIR/requirements.txt

ENV REIBUN_LOG_DIR $REIBUN_BASE_DIR/log
VOLUME ["$REIBUN_LOG_DIR"]

WORKDIR $REIBUN_SRC_DIR

ENTRYPOINT ["ipython"]
